# Generated by Django 3.2.4 on 2022-11-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Link')),
                ('refresh_interval', models.IntegerField(default=10, help_text='Status check interval (in secs)')),
            ],
            options={
                'verbose_name': 'Links',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
