# Generated by Django 3.2.4 on 2022-11-09 15:25

from django.db import migrations


def seed(apps, schema_editor):
    Links = apps.get_model('links', 'Links')

    Links.objects.create(link="https://google.com", refresh_interval=5)
    Links.objects.create(link="https://twitter.com", refresh_interval=10)
    Links.objects.create(link="https://facebook.com", refresh_interval=15)
    Links.objects.create(link="https://google.com/wrong", refresh_interval=10)


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed)
    ]
