# Generated by Django 3.2.4 on 2022-11-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_auto_20221109_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='status',
            field=models.IntegerField(default=200),
        ),
    ]
